{{ config(materialized='table') }}

SELECT
    VIDEO_ID,
    ANY_VALUE(CLEANED_TEXT) AS CLEANED_TEXT,
    ANY_VALUE(ARRAY_SIZE(TECH_TERMS_ARRAY)) AS TECH_TERM_COUNT,
    ANY_VALUE(ARRAY_SIZE(BOOK_NAMES_ARRAY)) AS BOOK_NAME_COUNT,
    ANY_VALUE(ARRAY_SIZE(SPLIT(CLEANED_TEXT, ' '))) AS WORD_COUNT,
    ANY_VALUE(LENGTH(CLEANED_TEXT)) AS CHAR_COUNT,
    MAX(INSERTED_AT) AS PROCESSED_AT
FROM {{ ref('stg_youtube_transcripts') }}
GROUP BY VIDEO_ID
